[2020-09-24 16:41:42,895][MainThread:139770072792392][task_id:django.utils.autoreload][autoreload.py:222][INFO][/usr/src/api/vuebackend/settings.py changed, reloading.]
[2020-09-24 16:41:43,797][MainThread:139984609828168][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-09-24 16:42:58,777][MainThread:139984609828168][task_id:django.utils.autoreload][autoreload.py:222][INFO][/usr/src/api/vuebackend/settings.py changed, reloading.]
[2020-09-24 16:42:59,683][MainThread:140034642259272][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-09-24 16:49:59,846][MainThread:140034642259272][task_id:django.utils.autoreload][autoreload.py:222][INFO][/usr/src/api/api/views.py changed, reloading.]
[2020-09-24 16:50:00,722][MainThread:139636254035272][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-09-24 16:51:33,799][MainThread:139636254035272][task_id:django.utils.autoreload][autoreload.py:222][INFO][/usr/src/api/api/views.py changed, reloading.]
[2020-09-24 16:51:34,797][MainThread:140428251012424][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-09-24 16:52:21,312][MainThread:140428251012424][task_id:django.utils.autoreload][autoreload.py:222][INFO][/usr/src/api/api/views.py changed, reloading.]
[2020-09-24 16:52:22,242][MainThread:140396985670984][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-09-24 16:52:26,852][Thread-1:140396938988320][task_id:django.request][log.py:228][ERROR][Internal Server Error: /api/get_logs/]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.7/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/src/api/api/views.py", line 378, in get
    return Response({l_dir:l_dir})
TypeError: unhashable type: 'list'
[2020-09-24 16:52:44,423][MainThread:140396985670984][task_id:django.utils.autoreload][autoreload.py:222][INFO][/usr/src/api/api/views.py changed, reloading.]
[2020-09-24 16:52:45,342][MainThread:140152990862664][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
[2020-09-24 16:54:26,110][MainThread:140152990862664][task_id:django.utils.autoreload][autoreload.py:222][INFO][/usr/src/api/api/views.py changed, reloading.]
[2020-09-24 16:54:27,057][MainThread:140170325564744][task_id:django.utils.autoreload][autoreload.py:598][INFO][Watching for file changes with StatReloader]
